version: '3'

services:
  lubimovka-frontend:
    build:
      context: ../../../
      dockerfile: config/docker/Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL:
        NEXT_PUBLIC_API_BASE_URL:
    image: lubimovka-frontend
    ports:
      - '3003:3000'
