name: Build and Deploy
concurrency:
  group: stage_deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lubimovka_frontend
  DEPLOY_PATH: /LUBIMOVKA

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    environment: stage_deploy
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variables
        run: |
          echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build and publish to Github Packages Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: config/docker/Dockerfile
          labels: runnumber=${GITHUB_RUN_ID}
          push: true
          build-args: |
            BASE_URL=${{ secrets.STAGING_BASE_URL }}
            API_BASE_URL=${{ secrets.STAGING_API_BASE_URL }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:staging
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    environment: stage_deploy
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Create ssh key
        # (SSH_KNOWN_HOSTS=ssh-keyscan -H сервер, SSH_PRIVATE_KEY - ключ с ПК, которому разрешен вход)
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Create application directory
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} mkdir -p ${{ env.DEPLOY_PATH }}
      - name: Copy configuration
        run: scp -r config/docker/staging/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ env.DEPLOY_PATH }}/stage
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ env.DEPLOY_PATH }}/stage/

            # Используем переменные окружения, сохраненные от CI/CD backend
            # Создание сети вынесено отдельно для возможности независимо перезапускать контейнеры (через external networks)
            # docker network create stage_db_network || true
            docker network create stage_swag_network || true

            # Установка приложения - frontend
            cp -rf ${{ env.DEPLOY_PATH }}/stage/lubimovka-frontend.service /etc/systemd/system/lubimovka-frontend.service
            systemctl daemon-reload
            systemctl restart lubimovka-frontend.service

            # После установки удаляем файлы
            rm ${{ env.DEPLOY_PATH }}/stage/lubimovka-frontend.service
