name: Build and Deploy
concurrency:
  group: prod_deploy
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: lubimovka_frontend
  DEPLOY_PATH: /LUBIMOVKA

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    environment: stage_deploy
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variables
        run: |
          echo REPOSITORY_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build and publish to Github Packages Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: config/docker/Dockerfile
          labels: runnumber=${GITHUB_RUN_ID}
          push: true
          build-args: |
            BASE_URL=${{ secrets.PRODUCTION_BASE_URL }}
            API_BASE_URL=${{ secrets.PRODUCTION_API_BASE_URL }}
            GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:production
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
